# -*- coding: utf-8 -*-
"""Assignment_7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IitUxlctVbuFuX74AdaCKAoMKHGKthqe
"""

import random as rd

size_siml = 1000000
no_pick_data = [0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]
one_pick_data = [0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]
two_pick_data = [0, 0, 1, 1, 1, 1, 2, 2, 2, 2]
# The above array is an array of integers, 0 representing the event of picking red ball, 1 representing the event of picking green ball,
# 2 representing the event of picking blue ball.
numb_three_red = 0
#The for loop goes through 1000000 iterations. 
for i in range(size_siml):
  sim_itr_1 = rd.randint(0, 11)
  if (no_pick_data[sim_itr_1] == 0):
    sim_itr_2 = rd.randint(0, 10)
    if (one_pick_data[sim_itr_2] == 0):
      sim_itr_3 = rd.randint(0, 9)
      if (two_pick_data[sim_itr_3] == 0) :
        numb_three_red += 1

  
  
# The variables below store the probability values based on simulations  
prob_three_red = numb_three_red / size_siml

print(" The following results are obtained from simulations")
print(f"(b) Choosing different terminals has a probability of : {prob_three_red}")

print("The following results are obtained theoretically")
print("(b) Choosing different terminals has a probability of : 0.0181819")
diff_var_diff = prob_three_red - 0.0181819
print(f"The difference between the simulations' and the theoretical values are : {diff_var_diff}")